### PR TITLE
[In-Progress] Fixing all the things

### PR DESCRIPTION
**Pull request by jameskolce**
I'll be adding more commits to fix the issues I can, it would be better to not merge yet.

### CODE REVIEW

**Comment by jameskolce** [comment]
No worries! I'll be adding more commits the next week too

**Comment by hlissner** [comment]
Looks great so far! Is it ready for a merge or would you like a little longer?

**Comment by jameskolce** [comment]
You can merge now if you want, I'll do more changes but I can open another pull request, because I'm not sure when I'll continue, perhaps the next neek.

**Comment by hlissner** [comment]
That's fine, I'm in no rush, so I'll hold out until then.

**Comment by jameskolce** [comment]
Hey @hlissner, I think you can merge changes, I want to continue working on it but I don't know when that will happen. So I think is better to merge now, once I get more changes I'll open a new PR 👍

**Pull request merged**
